# Generated by Django 3.1.7 on 2021-06-14 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_auto_20210614_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='place_order',
            fields=[
                ('placedOrder_id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.TextField()),
                ('address', models.TextField()),
                ('zipcode', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
