# Generated by Django 3.1.7 on 2021-06-14 11:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_place_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='place_order',
            new_name='placeOrder',
        ),
    ]
