# Generated by Django 3.1.7 on 2021-06-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210614_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
