# Generated by Django 3.1.7 on 2021-06-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_placeorder_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='total',
            field=models.PositiveIntegerField(default='0'),
            preserve_default=False,
        ),
    ]
