# Generated by Django 3.1.7 on 2021-06-16 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210615_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(blank=True, max_length=10, null=True)),
                ('shipped', models.CharField(blank=True, max_length=10, null=True)),
                ('inRoute', models.CharField(blank=True, max_length=10, null=True)),
                ('arrived', models.CharField(blank=True, max_length=10, null=True)),
                ('estimatedDate', models.DateField()),
                ('facilityNo', models.PositiveIntegerField(blank=True, null=True)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.placeorder')),
            ],
        ),
    ]
