# Generated by Django 3.1.7 on 2021-06-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='comment',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
