# Generated by Django 3.1.7 on 2021-06-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_orderstatus_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='estimatedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
