# Generated by Django 3.1.7 on 2021-06-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210617_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='arrived',
            field=models.CharField(blank=True, default='todo', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='inRoute',
            field=models.CharField(blank=True, default='todo', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='process',
            field=models.CharField(blank=True, default='done', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='shipped',
            field=models.CharField(blank=True, default='todo', max_length=10, null=True),
        ),
    ]
