# Generated by Django 3.1.7 on 2021-06-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210617_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='comment',
            field=models.TextField(default='Your Order is Confirmed...'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='estimatedDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='facilityNo',
            field=models.PositiveIntegerField(blank=True, default=151, null=True),
        ),
    ]
